### ISSUE TITLE
has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.material#80]
nach dem Update auf 1.0.3 ist mir noch folgendes aufgefallen
`

socketio.0 | 2021-07-28 18:32:30.392 | warn | (6488) State "material.0.control.theme" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
socketio.0 | 2021-07-28 18:32:24.195 | warn | (6488) State "material.0.control.page" has no existing object, this might lead to an error in future versions

`

**Comment by Apollon77** [comment]
@GermanBluefox It seems that these objects are not existing. They should be added to io-package.

Additionally please have a look in depth because e.g. control.page can be a string or object ... but we do not transport plain objects anymore in controller 3.3 and this might lead to other issues ... so you need to detect and convert object content if you have such a "string/object" mixed string

**Comment by GermanBluefox** [comment]
Please try 1.0.4

**Comment by crunchip77** [comment]
Mit v1.0.4 besteht der Fehler weiterhin
